server:
  port: 8020
spring:
  application:
    name: menu
  datasource:
    name: springcloud_order
    url: jdbc:mysql://localhost:3306/springcloud_order?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-calss-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true